config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :events
  resources :tickets

  get 'setting/index'
  post 'setting/upload'
  

  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :tickets
	has_attached_file :photo, :styles => { :small => "150x150>", :medium => "500x500>" },
                  :url  => "/assets/events/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/events/:id/:style/:basename.:extension"

	validates_attachment_presence :photo
	validates_attachment_size :photo, :less_than => 5.megabytes
	validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

	belongs_to :event
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :tickets

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/missing.png"
  do_not_validate_attachment_file_type :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :avatar
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  respond_to :js, :html

  def index
    @events = Event.all
    @events = @events.sort_by &:datetime
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit

  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    
    if @event.available_tickets > @event.total_tickets
      flash[:alert] = "The number of available tickets is greater than the amount of total tickets."
      redirect_to new_event_path
    elsif @event.datetime < DateTime.current
      flash[:alert] = "The date of the event cannot be set in the past."
      redirect_to new_event_path
    else
      @event.save
      respond_with(@event)
    end
  end

  def update
    # if params[:event][:available_tickets] > params[:event][:total_tickets]
    #   flash[:alert] = "The number of available tickets is greater than the amount of total tickets."
    #   redirect_to edit_event_path(@event)
    # else
      @event.update(event_params)
      respond_with(@event)
    # end
  end

  def destroy
    tickets = Ticket.all
    tickets.each do |ticket|
      if ticket.event_id == @event.id
        Ticket.destroy(ticket)
      end
    end
    
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:photo, :title, :event_type, :datetime, :venue, :available_tickets, :total_tickets, :user_id)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  respond_to :js, :html
  
  def index
    @tickets = Ticket.where(user_id: current_user.id)
    sorted_tickets = []
    events = Event.all.sort_by &:datetime
    events.each do |event|
      @tickets.each do |ticket|
        if event.id == ticket.event_id
          sorted_tickets.push(ticket)
        end
      end
    end
    @ticket = sorted_tickets
    respond_with(@tickets)
  end

  def show
    respond_with(@ticket)
  end

  def new
    @ticket = Ticket.new
    respond_with(@ticket)
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = current_user.id

    @event = Event.find(@ticket.event_id)
    @event.update_attribute :available_tickets, @event.available_tickets-@ticket.num_booked
    @event.save
    
    existing_ticket = Ticket.find_by({:event_id => @ticket.event_id, :user_id => @ticket.user_id})
    if existing_ticket.nil?
      @ticket.save
      respond_with(@ticket)
    else
      flash[:notice] = "Added #{existing_ticket.num_booked} ticket(s) to #{@ticket.num_booked} existing ticket(s)."
      existing_ticket.update_attribute :num_booked, existing_ticket.num_booked+@ticket.num_booked
      existing_ticket.save
      respond_with(existing_ticket)
    end
  end

  def update
    @ticket.update(ticket_params)
    respond_with(@ticket)
  end

  def destroy
    @ticket.destroy
    respond_with(@ticket)
  end

  private
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def ticket_params
      params.require(:ticket).permit(:event_id, :user_id, :num_booked)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<% Time.zone = 'MST' %>
<%= form_for @event, :html => { :multipart => true } do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :event_type %><br>
    <%= f.text_field :event_type %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br>
    <% Time.use_zone('MST') do %>
      <%= f.datetime_select :datetime, start_year: 2014, end_year: 2034, ampm: true, order: [:month, :day, :year] %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </div>

  <div class="field">
    <%= f.label :available_tickets %><br>
    <%= f.number_field :available_tickets, min: 0 %>
  </div>
    
  <div class="field">
    <%= f.label :total_tickets %><br>
    <%= f.number_field :total_tickets, min: 0 %>
  </div>

  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>

  <div class="actions"> 
    <%= f.submit %>
  <div>

<% end %>

app/views/events/edit.html.erb
<style>
.event-form {
    width: 50%;
    min-width: 500px;
    max-width: 1400px;
    margin-left: auto;
    margin-right: auto;
    margin-top: 30px;
    border: outset;
    padding-left: 50px;
    padding-bottom: 15px;
    border-radius: 20px;
}
</style>

<div class="event-form">
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</div>

app/views/events/index.html.erb
<style>
#events_page {
    width: 90%;
    min-width: 500px;
    max-width: 1400px;
    margin-left: auto;
    margin-right: auto;
    margin-top: 30px;
    border: outset;
    padding-left: 50px;
    padding-bottom: 15px;
    padding-top: 25px;
    border-radius: 20px;
}

table th{
  padding: 0 30px;
  border-bottom: double;
}

tbody td{
  padding: 0 30px;
}

.num-tickets {
  text-align: center;
}
</style>



<div id="events_page">
  <% if user_signed_in? %>

  <p>Your TicketList is listed by event time. Events with a date and time older than the current date and time will not be displayed. Click on the thumbnail of an event to find out more.</p>

<table>
  <% if !@events.empty? %>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% else %>
  There are no events. Create one to get started.
  <% end %>
  
  <% Time.zone = 'MST' %>
  <tbody>
    <% @events.each do |event| %>
      <% if event.datetime >= DateTime.current %>
        <tr>
          <td><%= link_to (image_tag event.photo.url(:small)), event %></td>
          <td><%= event.title %></td>
          <td><%= link_to 'Show', event %></td>
          <% if event.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_event_path(event) %></td>
            <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %><br><br><p>Want to see your booked tickets? <%= link_to 'View now.', tickets_path %></p>
  <% else %>
	An online ticket booking web application.
  <% end %>
</div>

app/views/events/new.html.erb
<style>
.event-form {
    width: 50%;
    min-width: 500px;
    max-width: 1400px;
    margin-left: auto;
    margin-right: auto;
    margin-top: 30px;
    border: outset;
    padding-left: 50px;
    padding-bottom: 15px;
    border-radius: 20px;
}
</style>

<div class="event-form">
<h1 style="font-family: Times New Roman;">New Event</h1>


<%= render 'form' %>

<%= link_to 'Back', events_path %>

</div>

app/views/events/show.html.erb
<style>
  #event {
    width: 90%;
    min-width: 500px;
    max-width: 1400px;
    margin-left: auto;
    margin-right: auto;
    margin-top: 30px;
    border: outset;
    padding-left: 50px;
    padding-bottom: 15px;
    padding-top: 25px;
    border-radius: 20px;
  }
</style>

<div id="event">

<p>All ticket sales are final.</p>

<p><%= image_tag @event.photo.url(:medium) %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Event type:</strong>
  <%= @event.event_type %>

</p>

<% Time.zone = 'MST' %>
<p>
  <strong>Date and time:</strong>
   <%= @event.datetime.strftime("%m/%d/%Y %I:%M%p") %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @event.venue %>
</p>

<p>
  <strong>Available tickets:</strong>
  <%= @event.available_tickets %>
</p>

<p>
  <strong>Total tickets:</strong>
  <%= @event.total_tickets %>
</p>

<p>
  <%= form_tag(tickets_path, :method => :post) do %>
  <%= hidden_field(:ticket, :event_id, :value => @event.id) %>
  <% if @event.available_tickets == 0 %>
    No more available tickets.
  <% else %>
    <%= number_field(:ticket, :num_booked, value: 1, in: 1...@event.available_tickets+1) %>
    <%= submit_tag("Book") %>
  <% end %>
<% end %>

</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<style>
#user_nav {
    width: 25%;
    min-width: 500px;
    max-width: 1400px;
    margin-left: auto;
    margin-right: auto;
    margin-top: 30px;
    text-align: center;
}

.notice {
  font: green;

.alert {
  font: red;
}
}

.background1 {
  background-color: red;
}

footer td{
  text-align: center;
  padding: 0 15px;
}

footer table{
  margin: 0 auto;
  padding-bottom: 0px;
}

footer {
  background-color: black;
  color: white;
}
</style>

<head>
  <title>Ticketlist</title>
  <%= stylesheet_link_tag    'application.css.scss', media: 'all', 'data-turbolinks-track' => true %>

<!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body style="background-image: url(back.jpg)">
<%= image_tag "ticketlistlogo.png" %>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="height: 40px">
      <div class="navbar-header">
        <%= link_to (image_tag "ticketlistlogo.png"), events_path %>
        <a class="navbar-brand" href="#" style="font-size: 40px">TicketList</a>
      </div>
      <div class="collapse navbar-collapse">
      </div><!--/.nav-collapse -->
</div>

<div class="backgroud1">


<div id="user_nav">
  <% if user_signed_in? %>
    <%= image_tag current_user.avatar.url(:thumb) %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
    <%= link_to "Settings", edit_user_registration_path %>
  <% else %>
    Need an account? <%= link_to "Sign up.", new_user_registration_path %><br>
    Already have an account? <%= link_to "Log in.", new_user_session_path %>
  <% end %>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>


<br>
<br>
 
  


</div>

</body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :num_booked %><br>
    <%= f.number_field :num_booked %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<style>
#tickets_page {
    width: 90%;
    min-width: 500px;
    max-width: 1400px;
    margin-left: auto;
    margin-right: auto;
    margin-top: 30px;
    border: outset;
    padding-left: 50px;
    padding-bottom: 15px;
    padding-top: 25px;
    border-radius: 20px;
}

table {
  width: 90%;
}

table th{
  border-bottom: double;
}

tbody td{
  padding: 0 30px;
}

.num-tickets {
  text-align: center;
}

#caption1{
  margin-left: 5%;
}
</style>

<div id="tickets_page">
<% Time.zone = 'MST' %>

<p>Your booked tickets are listed by event time.</p>

<table>
  <% if !@tickets.empty? %>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Event type</th>
        <th>Date and time</th>
        <th>Venue</th>
        <th>Number of tickets booked</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  <% else %>
    There are no tickets. Book a ticket from an event.
  <% end %>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <% event = Event.find(ticket.event_id) %>
        <td><%= link_to (image_tag event.photo.url(:small)), event %></td>
        <td><%= event.title %></td>
        <td><%= event.event_type %></td>
        <td><%= event.datetime.strftime("%m/%d/%Y %I:%M%p") %></td>
        <td><%= event.venue %></td>
        <td><%= ticket.num_booked %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<br>
<br>

<p>Want more new and exciting events? <%= link_to 'View now.', events_path %></p>

</div>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<style>
  #ticket {
    width: 90%;
    min-width: 500px;
    max-width: 1400px;
    margin-left: auto;
    margin-right: auto;
    margin-top: 30px;
    border: outset;
    padding-left: 50px;
    padding-bottom: 15px;
    padding-top: 25px;
    border-radius: 20px;
  }
</style>

<div id="ticket">

<% Time.zone = 'MST' %>
<% event = Event.find(@ticket.event_id) %>

<p><%= link_to (image_tag event.photo.url(:medium)), event %></p>


<p>
  <strong>Event title:</strong>
  <%= event.title %>
</p>

<p>
  <strong>Event type:</strong>
  <%= event.event_type %>
</p>

<p>
  <strong>Event date:</strong>
  <%= event.datetime.strftime("%m/%d/%Y %I:%M%p") %>
</p>

<p>
  <strong>Event venue:</strong>
  <%= event.venue %>
</p>


<p>
  <strong>Number of tickets booked:</strong>
  <%= @ticket.num_booked %>
</p>


<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

</div>